### ISSUE TITLE
Authorize Now button never visible on settings

### ISSUE THREAD

**Issue by aster-anto** [robweber/xbmcbackup#134]
'Authorize Now' button never getting enabled on settings.

Steps to reproduce:

1. Do a fresh plugin install
2. From settings page - provide google client id/secret
3. Observe 'Authorize Now' button is not appearing.

Could be the case with dropbox as well - however, I haven't tested it.
Noticed duplicate id in settings.xml. Tested against version 1.1.2

Relevant part from logs:
_19:56:37.458 T:3577729872 WARNING: CAddonSettings[script.xbmcbackup]: failed to parse visible condition "gt(-9,1)" of old setting definition for "remove_auth_button"
19:57:43.382 T:4098510864 WARNING: CAddonSettings[script.xbmcbackup]: cannot reference setting (relative index: -8; absolute index: -1) in another category in old setting condition "eq(-8,3)" for "remove_auth_button"
19:57:43.383 T:4098510864 WARNING: CAddonSettings[script.xbmcbackup]: failed to parse visible condition "eq(-8,3)" of old setting definition for "remove_auth_button"
19:57:43.383 T:4098510864 WARNING: CAddonSettings[script.xbmcbackup]: cannot reference setting (relative index: -9; absolute index: -2) in another category in old setting condition "gt(-9,1)" for "remove_auth_button"
19:57:43.383 T:4098510864 WARNING: CAddonSettings[script.xbmcbackup]: failed to parse visible condition "gt(-9,1)" of old setting definition for "remove_auth_button"
20:16:32.740 T:4098510864 WARNING: CAddonSettings[script.xbmcbackup]: cannot reference setting (relative index: -9; absolute index: -2) in another category in old setting condition "gt(-9,1)" for "remove_auth_button"
20:16:32.740 T:4098510864 WARNING: CAddonSettings[script.xbmcbackup]: failed to parse visible condition "gt(-9,1)" of old setting definition for "remove_auth_button"_

**Comment by robweber** [comment]
I can't believe I missed that. I definitely see what you're saying. I'll test out on my end to make sure that's what is happening here but that looks like the problem.

**Comment by robweber** [comment]
I fixed the settings, although on Kodi 17 the button was working for me without that being fixed. What version of Kodi are you on? Could you try the [new settings](https://github.com/robweber/xbmcbackup/blob/master/resources/settings.xml) file and see if it works for you now?

**Comment by aster-anto** [comment]
ah - looks like its my bad then, I'm on a Kodi 18 alpha build.
Tried it with latest settings file, but with that 'Authorise Now' and 'Delete Authorisation Info' are always visible.
I guess its safe to close this as it could be a Kodi 18 only thing ?

**Comment by robweber** [comment]
That sounds about right. If everything is working you should get "authorize" and "delete" as enabled if you have Google Drive or Dropbox selected as the storage repository. I'll go ahead and push this change since its likely to be an issue going into Kodi 18. 17 must have been more lenient on if settings ids overlapped. 

You're able to get it authorized and stuff now right?

**Comment by aster-anto** [comment]
yes - got it authorized etc. Great work with the plugin mate. Thanks

**Comment by isaac-mm** [comment]
Hi, I'm using xbmcbackup 1.1.2 installed from kodi repository in a Android TV with Kodi 17 and I can't see the Authorize now button in google drive, in dropbox section appears but in google drive not. I put my Client ID and Secret ID but cannot connect because it says is not authorized.

**Comment by kinv** [comment]
Autherize now still not there on liea 18. Edited the settings.xml as above and it is fixed. Could you push this to the kodi repo?

**Comment by robweber** [comment]
Yea getting this done is on my "to do" list. Not trying to be a big complainer but getting stuff pushed to the repo isn't as easy as it used to be. Anyone with a keen eye will notice I've had a pull request for one of my other addons open there for a while now because it seems every time I submit it there is some minor thing that needs tweaking before it will get merged in. This addon is way more complicated code-wise so I've been delaying even trying.
