### ISSUE TITLE
Since Kodi v19.0 - Restore now offers two options: Backup Set Leia 18.5 and Backup Set.

### ISSUE THREAD

**Issue by sammydc77** [robweber/xbmcbackup#188]
Before working on a new issue I'm probably going to ask you all this stuff anyway, probably just easier to provide it now.....

**Describe the problem**

Hello:

I just update to v1.66 today.  But this issue has not changed since Kodi v19.0 upgrade.

Why two options?  How do they differ?  Do I select both or one?

I just submitted another issue, prior to this one, with my other pertinent information.  I did not want to duplicate.

Regards,

Joseph

**Platform and Kodi version**
What OS and Kodi version are you using? (Rpi, Android, etc)

**Link to Debug Log**
Don't just post the whole thing here,  use [https://paste.kodi.tv](https://paste.kodi.tv)

**Comment by robweber** [comment]
Does this sort it out for you: https://github.com/robweber/xbmcbackup/wiki/Restoring-Files? 

In short there are two layers to a restore. The first is selecting the backup archive, the next is the sets within that archive. If you're using the Advanced Editor these could be named anything. With the simple editor you get names like "addons" or "config files". This defines the files that will be restored.

**Comment by sammydc77** [comment]
Hello Rob:

I really appreciate your reply. First, I want to say, I have been using
your Backup exclusively with Kodi, for years, it is the only one I have
come to trust.  At this point, I can not open the Advanced Editor, due to
the Python Error: https://paste.kodi.tv/mivoboxazo.kodi, please find the
issue near the bottom of this Debug Log.  I have been restoring both set,
when needed, so it seems I should continue this practice.  The only issue
left, is why Kodi v19.0 Python has an issue with the Advanced Editor?
Thanks for clearing up part of my question.

Regards,

Joseph

**Comment by robweber** [comment]
Glad you're finding it useful! I'll review this problem in the other issue you opened.

**Comment by sammydc77** [comment]
Hello Rob:

Thank You, and I look forward to your findings on the other issue.  Your
time is appreciated.

Regards,

Joseph

**Comment by sammydc77** [comment]
Hello Rob:

I have included my Kodi Debug Log, and four Images [PDF].  The first run, I
got an error, when trying the Advanced Editor, from the Main App Screen
[Image I], but when I did the same from the Settings Screen, no issues.  I
tried Edit on both sets, but found they each had duplicate parameters, so
it appears I am duplicating the backup, each time it runs [about 1.68GB].
I tried to use the hastebin at kodi.tv [https://paste.kodi.tv/], but it
would not save the Debug Log, it always gave me [something went wrong],
when I tried to save.  I thought that would have been easier for you to
peruse my log, so I zipped it for you.  All in all, it works okay, baring
the one issue.  I am still unclear as to the two sets, via Advanced, as to
how to separate the two groups [apps / system data]?  Please let me know if
I can be of any further assistance,  I hope this helps.

Also, I found an issue with Kodi v19.0, that I reported to Kodi, but the
refuse to consider it an issue, because they want me to strip my system
clean of all Add-ons.  In Kodi v18.9, there were no issues seeing the
External SSD Drive, by Label and/or UUID/GUID, v19.0 can not even see the
External SSD Drive. [G-Technology 1TB G-DRIVE mobile SSD].  Attached [PDF] is
the detail I had given them, maybe you might know where I can go to fix
this issue, as I was placing my Backups on the External SSD Drive.

Update ;  Apparently, your email system, will not allow me to send any
attachments [the hastebin would have  been very handy right now.].  I will
try another way to get you,at least the  relevant portion of the log.

Regards,

Joseph

**Comment by sammydc77** [comment]
Rob:

I pulled the relevant portion from my log and had to save it as a Python
[.py], with Code Pad Text Editor.  I hope you can read it.

Joseph

**Comment by robweber** [comment]
I bet that is Github stripping stuff out as it converts all this as part of the Issue. I bet attachments are pulled out. 

Getting to the Advanced Editor via the settings but not through the launcher makes sense - at least for now. I should have clarified as I hadn't gone through and cleaned up everything nicely just yet. If that seems to fix things up, at least for the Advanced Settings editor, I'll start working on that so get it release ready. 

Regarding the different backup sets. Depending on how you want things to work you could just delete the duplicate set or modify them so that one is only system stuff and one is only addons (or whatever division you want). If you were using the Simple mode it would make a different set for each file type (Addons, Addon Data, etc). If you just want to start all over you can select the option to copy the Simple editor config to the Advanced Editor and then modify as needed. The benefit to the different sets comes more on the restore end. There are times where you may just want to restore the config files but not touch the addon data or something like that.

**Comment by sammydc77** [comment]
Rob:

I understand the Github limitations.  Hopefully, you were able to see some
of what I had sent you.  I will explore the Advanced Options, more in depth.

Joseph
