### ISSUE TITLE
Dropbox error "Authorize this remote service in the settings first"

### ISSUE THREAD

**Issue by stvg88** [robweber/xbmcbackup#207]
Before working on a new issue I'm probably going to ask you all this stuff anyway, probably just easier to provide it now.....

**Describe the problem**
When choosing Dropbox as Remote Path, after entering the app key and app secret > Click OK > open Settings again (app key and app secret still there) > Authorize Now, the error message appears "Authorize this remote service in the settings first". Looks like it's similar to [this bug](https://github.com/robweber/xbmcbackup/issues/200)

**Platform and Kodi version**
Issue happens on both Windows 10 and Android TV, Kodi 19.3

**Link to Debug Log**
[Debug Log](https://paste.kodi.tv/docaqafaje.kodi)

**Comment by robweber** [comment]
Been a while since I've looked at #200. Although the issue itself is closed, and the code merged in, it doesn't appear that this fix was every pushed to the Kodi repo. I see in the changelog it's still listed as Unreleased. 

If it is the same bug updating to the current codebase from Github might sort it out. I'll work on getting these changes pushed to the Kodi repo.

**Comment by robweber** [comment]
I do have a PR open for this, monitoring for when it gets merged: https://github.com/xbmc/repo-scripts/pull/2198

**Comment by robweber** [comment]
Closing this as the PR has now been merged so this in the main repo version.
