### ISSUE TITLE
Ajouter un libeller sur le nom de l'archive zip

### ISSUE THREAD

**Issue by KodiPerso** [robweber/xbmcbackup#218]
Bonjour j'ai plusieur KODI installer sur divers Box Tel Télévision 
J'effectuer toute mes sauvegarde sur mon NAS au même endroit smb.
Je souhaiterez que mes sauvegarde porte le nom du matériel exemple 202318051800Nvidia.zip
je cherche quelle fichier modifier dans l'addon de backup pour ajouter a la fin une information complémentaire

202318051800Nvidia.zip
202318051837TVSALONzip
202318051840TELSAMSUNG.zip

Merci pour votre aide

**Comment by robweber** [comment]
This is a great idea - I'm sure others could use it as well. You probably thought of this but using the same directory for multiple Kodi installs will affect the backup rotation. If you have a rotation of 5 but are doing 3 different Kodi installs you'll want to change the rotation to 15 so that you get 5 of each one. The rotation works by sorting the files and removing the oldest.
