### ISSUE TITLE
Easier Dropbox authentification

### ISSUE THREAD

**Issue by claell** [robweber/xbmcbackup#69]
I was wondering whether there is a way to get Dropbox (and other cloud services) to work easier, without having to create an own app and typing in key and secret.

**Comment by robweber** [comment]
I took another look into this just for fun. Short answer is "no", but read the explanation below. 

In the early days of this addon I attempted to get my own Dropbox secret/key and publish them with the app. This way all the user had to do was authorize via Oauth2. Dropbox didn't like this. As an open source project I could not obscure or hide my key/secret information as all the code is publically available. I had to resort to the method we use now of each person making their own. 

I spent some time looking in to how other projects do this, and it appears they are in the same boat. If your code is compiled before distribution you can get away with not publishing the key/secret in your source code and inserting them at compile time with a script. Since python files are always readable once downloaded by the end user this is not an option. Dropbox will simply not authorize the project with a production key/secret given it's distribution method. Other cloud services might, but in the case of something like Google Drive - I'm not going to be responsible for API charges due to use. Right now those are the only 2 cloud file systems supported.

**Comment by claell** [comment]
Thanks for your detailed answer. Sad that Dropbox doesn't want the keys published.

Since I already have created an app now, it does not matter for me anymore.

But when setting up a new device, I would like to have an easier way to authenticate than grabbing the link from the log. Maybe you could display it in the addon (with link shortening?) or find a way to send it to the user?
