### ISSUE TITLE
Incremental backups

### ISSUE THREAD

**Issue by claell** [robweber/xbmcbackup#70]
I just backed up my setup and it took around 3 hours, since it had to upload everything to dropbox. So I thought that incremental backups which only back up changed or new files would be nice, so the backup does not take that much time.

**Comment by claell** [comment]
Is this possible?

**Comment by robweber** [comment]
Sorry for the delay - not enough hours in the day. 

Incremental backups would be awesome, however the problems they would create require some careful thinking in regards to the restore process. I guess consider the following scenerios: 

1) Zip files - only way to look in those is to have the zip file available locally. that would mean downloading, and examining every zip file in the backup chain to get a list of modified dates for the incremental. This problem goes for remote files in general as not all remote libraries expose the created/modified times of files. 

2) Restore operations - restore operations would require pulling in the full and incremental files from the chain, plus figuring out what files were needed. 

3) User error - what if you delete a part of the chain, or the full file? 

4) Deleted files - what happens if file A from the full is deleted when one of the later incrementals is run? When the restore happens all these archives get combined and there is file A again. Deleted files will also need to be kept track of so we can create a full snapshot of the files at the time of the incremental. 

Full blown backup software gets around these issues by creating their own IO libraries to get the data they need; plus they often bundle everything within their own archive types so that the user can't "muck around" and destroy file chains. Not saying this won't ever happen, but doing one-off style backups is much simpler than worrying about the issues with incrementals. Feel free to throw out solutions to these issues on the forum page (http://forum.kodi.tv/showthread.php?tid=129499)  - patches welcome :)

**Comment by claell** [comment]
Alright, thanks for the explenation.

Since it would be optional, there is not that much danger because of user errors.

I know this option from Ubuntu's built in Deja-dup, where it works pretty well. Maybe there are projects that have already realised this and you could use their work?
