### ISSUE TITLE
How to "Check log for Dropbox authorize URL" on non-jailbroken iOS

### ISSUE THREAD

**Issue by ryandesign** [robweber/xbmcbackup#87]
I'm trying to import my Kodi settings to Kodi on iOS. I don't want to have to configure all the settings on the iOS device manually.

I used Backup on my main Kodi machine to create a backup to Dropbox. This worked fine, after jumping through the hoop of creating a Dropbox developer app and entering its key and secret.

Now, trying to restore that backup in Kodi on the iOS device, I'm unsure how this is meant to work. It says "Check log for Dropbox authorize URL / Click OK when authorized". This was easy enough to do on a computer, but how would I check the Kodi log on a non-jailbroken iOS 9.3 device? I've installed the "Log Viewer for Kodi" add-on, but of course I cannot launch it without first clicking Backup's OK button. I cannot find any place in iTunes or iFunBox where I can see any Kodi settings files or logs.

**Comment by robweber** [comment]
That is a pretty odd problem. Not exactly sure how to accommodate this one with the current version of the program. 

I'm going to flag this as "wontfix" as this is not going to get changed in the current iteration. I'm leaving it on the "future planning" board though.

**Comment by ryandesign** [comment]
If you wontfix this, then I don't understand how to access my SMB-hosted media and my MySQL-hosted media library from Kodi on iOS. The only way I know of to access that is to edit the config files, which on a non-jailbroken device there does not seem to be any provision to do.

**Comment by robweber** [comment]
Ok, I see where you're going with this. Due to how the current oauth system works fixing this for the current addon just isn't a realistic option right now. I've tried various options in the past, none of them really worked. 

That being said, if your goal is to just try and get your config files updated so you can use advancedsettings.xml entries or update your media sources then I think I can help you. Within Kodi there is a file manager. I would get your config files onto an smb share on the current network of your iOS device. You should be able to use the file manager to copy the files from this smb share to the right locations all within Kodi. I've never had to navigate an iOS file system but this link should help you find where the files need to go: http://kodi.wiki/view/userdata

**Comment by robweber** [comment]
Just saving this here for later. I think implementing tiny URL as a shortener will allow the authorization to be displayed on screen. 

https://pypi.python.org/pypi/TinyUrl/0.1.0 

Will probably need an additional helper module.
