### ISSUE TITLE
Restore temp extract folder needs deleting 

### ISSUE THREAD

**Issue by unlocKing** [robweber/xbmcbackup#95]
When doing a restore from a zip it extracts to the temp folder first before copying across.. This also leaves the restore contents in the temp folder making it nearly impossible to delete using any maintenance tool, as it just loops trying to clear cache.

Need to delete the temp extract folder after copying across the restore successfully.

Android issue.

**Comment by robweber** [comment]
Can you prove this is the case. Looking at the code [starting here](https://github.com/robweber/xbmcbackup/blob/master/resources/lib/backup.py#L293) the steps appear to be in order

1. Copy zip file
2. [Extract zip file](https://github.com/robweber/xbmcbackup/blob/master/resources/lib/backup.py#L311)
3. Proceed with restore
4. [Delete the temp folder](https://github.com/robweber/xbmcbackup/blob/master/resources/lib/backup.py#L443) that was extracted

What kind of loop are you encountering? Keep in mind there are issues related to Kodi where the directory list contents are sometimes cached on certain systems and they don't already return correctly when using "exists()" when files are added/removed. This was fixed in Krypton I believe.

**Comment by unlocKing** [comment]
4 is not happening..

The loop is when using any maintenance cleaner tries to delete the files in the temp restore folder in cache.

This keeps going through each folder of the temp restore folder, which can forever as you are aware of the thousands of folders that are in a full backup.

**Comment by robweber** [comment]
Is the maintenance tool an addon in Kodi or some other OS specific thing?

**Comment by unlocKing** [comment]
3rd party addons.. 

I would've messaged the addon authors but the the real issue is with the restore function not doing number 4 (deleting the temp folder) all the time. 

If nobody else has mentioned it and you can not replicate it, then feel free to close this and next time I notice it I'll post the logs.

**Comment by robweber** [comment]
Tried this on a few different platforms and can't seem to replicate. Feel free to re-open if needed.
